name: Publish a NuGet Package

on:
  release:
    types: [ published ]

env:
  BRANCH: master

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore

    - shell: pwsh
      name: Create SNK File
      env:
        SNK: ${{ secrets.snk }}
      run: |
        $snk = [Convert]::FromBase64String("$env:SNK")
        Set-Content "Solution Items\GiGraph.snk" -Value $snk -AsByteStream

    - name: Build NuGet Package
      run: dotnet pack GiGraph.Dot\GiGraph.Dot.csproj --configuration Publish -p:Repository=${{ github.repository }} -p:Branch=${{ env.BRANCH }} -p:Commit=${{ github.sha }}

    - name: Publish NuGet Package
      run: dotnet nuget push GiGraph.Dot\bin\Publish\GiGraph.Dot.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_api_key }}